version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    volumes:
      - ./src:/go/src/work
    depends_on: 
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - "./docker/data/mongo:/data/db"
    ports:
        - "27017:27017"
volumes:
  mongodata:
    driver: local