version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    volumes:
      - ./src:/go/src/work
    depends_on: 
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - "./docker/data/mongo:/data/db"
    ports:
        - "27017:27017"
  app:
    image: nginx:latest
    container_name: "app"
    ports:
      - "9000:80"
    volumes:
      - ./src:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  node:
    image: node:10
    container_name: node
    tty: true
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app
volumes:
  mongodata:
    driver: local